name: Auto Deploy Backend
on:
  workflow_run:
    workflows: ["Security Check"]
    types: [completed]

jobs:
  security_check:
    name: Security Check
    uses: ./.github/workflows/security-check.yml
    
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to VPS
        run: |
          echo "Deploying backend..."
          cd  ~/project/back
          git pull origin master
          docker-compose down
          docker-compose up -d --build
          echo "Backend deployed successfully"
